name: Build

on:
  push:
    branches:
      - master
      - dev

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Run Unit tests
        run: bash ./gradlew test --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Assemble app debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload app APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Assemble Android Instrumentation Tests
        run: bash ./gradlew assembleDebugAndroidTest
      - name: Upload Android Test APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

  firebase:
    name: Run UI tests with Firebase Test Lab
    needs: apk
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Download app APK
        uses: actions/download-artifact@v4
        with:
          name: app-debug
          path: .
      - name: Download Android test APK
        uses: actions/download-artifact@v4
        with:
          name: app-debug-androidTest
          path: .
      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: Login to Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
      - name: Run robo Tests in Firebase Test Lab
        run: gcloud firebase test android run --type robo --app app-debug.apk --device model=Pixel2,version=28,locale=en,orientation=portrait